# _config.yml - configuration for my personal blog (cade.site)
#
# feel free to copy my entire project:
#   * https://github.com/cadebrown/cadebrown.github.io
#
# @author: Cade Brown <me@cade.site>


# -*- SITE -*-

# your website's name
# NOTE: i use my full URL, but if you have a catchy name, use it here
name: "cade.site"

# the URL of this blog (normally <user>.github.io, but may be a custom URL too)
displayurl: "cade.site"

# description of this blog (i.e. a medium text for SEO)
desc: "My personal website and blog, covering my programming, research, and digital artistry"

# the shell prompt to use while highlighting
shellprompt: "sh $"

# -*- ACCOUNTS/LINKS -*-

links:
  # your primary email
  # (we only assume you have this one)
  email: "me@cade.site"
  # GitHub username, or username/project
  github: cadebrown
  # Twitter username
  twitter: dev_ceb
  # Instagram username
  instagram: dev_ceb

# Disqus ID (comment to disable)
disqus: cadesite

# Google Analytics ID (comment to disable)
googleanalytics: G-DB8V1YFP76

  
# -*- RENDERING -*-

# renderer settings
markdown: kramdown
kramdown:
  parse_block_html: true
  # disable the default syntax highligher (since we use Prism.js)
  syntax_highlighter_opts:
    disable: true

# the default theme to use for the site (see 'css/main.css')
# other nice values are: 'chalkboard' (dark theme), 'whiteboard' (light theme)
theme_default: 'chalkboard'


# -*- POSTS -*-

# permalink format for a title
#permalink: /:year/:month/:day/:title
#permalink: /:year/:title
permalink: /:title


# pagination settings
paginate: 64
#paginate_path: /page-:num
paginate_path: "/blog/page:num/"


# seperator that tells where the 'more' text ends for description generation
# NOTE: should be an HTML comment
sep_more: <!--more-->

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from
